const DAYS_TO_UPDATE = 10

const FILENAME_FROM = {
  BADGE: 'BADGE',
  TRAINING_ID: 'TRAINING_ID',
  DATE_COURSE_ID: 'DATE_COURSE_ID'
}

const SCOPE = {
  UPLOAD_ONLY: 'UPLOAD_ONLY',
  DOWNLOAD_ONLY: 'DOWNLOAD_ONLY',
  UPLOAD_AND_DOWNLOAD: 'UPLOAD_AND_DOWNLOAD'
}

module.exports = { DAYS_TO_UPDATE, FILENAME_FROM, SCOPE }
